"""Renders the human-facing site/index.md projection, the bundle overview.md,
and the README.md AUTO-GENERATED counts table.

Human-facing output is kept to a single Markdown projection (no parallel
HTML) so there is only one artifact to keep in sync with the corpus; GitHub
renders it directly.
"""

from __future__ import annotations

from pathlib import Path

from .errors import CorpusError
from .corpus import counts_by

EPISTEMIC_EMOJI = {
    "recorded_decision": "\U0001f7e6",  # blue square
    "execution_verified": "\U0001f7e2",  # green
    "cross_source_corroborated": "\U0001f7e1",  # yellow
    "single_source_observation": "\U0001f7e0",  # orange
    "model_inference": "\U0001f7e4",  # brown
    "conflicting": "\U0001f534",  # red
}
CONFORMANCE_EMOJI = {"matched": "✅", "drifted": "\U0001f534", "not_checked": "❔"}

README_COUNTS_TABLE_START = (
    "<!-- AUTO-GENERATED:COUNTS_TABLE:START "
    "(generated by `evidence-docs generate` from manifest.json counts; manual edits "
    "are overwritten on the next generate) -->"
)
README_COUNTS_TABLE_END = "<!-- AUTO-GENERATED:COUNTS_TABLE:END -->"


def md_escape_inline(s) -> str:
    """Minimal escaping for Markdown headings/table cells.

    Backticks inside statement text are intentionally left alone so inline
    code (e.g. `if (saved && this.scopeId)`) still renders as code on GitHub.
    """

    return str(s).replace("|", "\\|")


def render_provenance_line_md(prov: dict, repo_relative_prefix: str, repo_internal_kinds: set) -> str:
    kind = prov["source_kind"]
    uri = prov["uri"]
    selector = prov.get("selector")
    if kind in repo_internal_kinds:
        location = f"[`{uri}`]({repo_relative_prefix}{uri})"
    else:
        location = f"`{uri}`"
    if selector:
        return f"- `{kind}` {location} — {md_escape_inline(selector)}"
    return f"- `{kind}` {location}"


def render_observation_md(obs: dict, repo_relative_prefix: str, repo_internal_kinds: set) -> str:
    status = obs["epistemic_status"]
    conf = obs["conformance_status"]
    status_badge = f"{EPISTEMIC_EMOJI.get(status, '⬜')} `{status}`"
    conf_badge = f"{CONFORMANCE_EMOJI.get(conf, '❔')} `{conf}`"
    provenance_md = "\n".join(
        render_provenance_line_md(p, repo_relative_prefix, repo_internal_kinds) for p in obs["provenance"]
    )
    lines = [
        f'<a id="{obs["observation_id"].lower()}"></a>',
        f"### {obs['observation_id']} · `{obs['claim_kind']}` · {status_badge} · {conf_badge}",
        "",
        obs["statement"],
        "",
        "**provenance:**",
        "",
        provenance_md,
    ]
    if obs.get("negation_check"):
        lines += ["", "**negation check:**", "", obs["negation_check"]]
    return "\n".join(lines)


def render_topic_overview_table_md(topic_observations: list[dict]) -> str:
    lines = ["| ID | claim_kind | epistemic_status | conformance_status |", "|---|---|---|---|"]
    for obs in topic_observations:
        status = obs["epistemic_status"]
        conf = obs["conformance_status"]
        lines.append(
            f"| [{obs['observation_id']}](#{obs['observation_id'].lower()}) | "
            f"`{obs['claim_kind']}` | {EPISTEMIC_EMOJI.get(status, '⬜')} `{status}` | "
            f"{CONFORMANCE_EMOJI.get(conf, '❔')} `{conf}` |"
        )
    return "\n".join(lines)


def render_markdown(
    topics: dict[str, dict],
    observations: dict[str, dict],
    generated_at: str,
    repo_commit: str,
    repo_relative_prefix: str,
    repo_internal_kinds: set,
    corpus_title: str,
    regen_command: str,
) -> str:
    by_topic: dict[str, list[dict]] = {tid: [] for tid in topics}
    for oid in sorted(observations):
        by_topic[observations[oid]["topic_id"]].append(observations[oid])

    toc = "\n".join(f"- [{tid} — {topics[tid]['title']}](#{tid.lower()})" for tid in sorted(topics))

    sections = []
    for tid in sorted(topics):
        topic = topics[tid]
        topic_obs = by_topic[tid]
        observation_blocks = "\n\n".join(
            render_observation_md(obs, repo_relative_prefix, repo_internal_kinds) for obs in topic_obs
        )
        sections.append(
            f'<a id="{tid.lower()}"></a>\n\n'
            f"## {tid} — {topic['title']}\n\n"
            f"{topic['description']}\n\n"
            f"{render_topic_overview_table_md(topic_obs)}\n\n"
            f"{observation_blocks}"
        )

    sections_text = "\n\n".join(sections)
    return f"""# {corpus_title}

> **All claims below carry their own `review_status`; anything still
> `unreviewed` is AI-generated content that has not had human sign-off.**
> Treat it accordingly.

Regenerate with:

```bash
{regen_command}
```

generated_at: `{generated_at}` / repo_commit: `{repo_commit}`

## Topics

{toc}

{sections_text}
"""


def render_overview_md(topics: dict[str, dict], claims: list[dict], generated_at: str, repo_commit: str) -> str:
    lines = [
        "# corpus overview",
        "",
        f"- generated_at: {generated_at}",
        f"- repo_commit: {repo_commit}",
        f"- topics: {len(topics)}",
        f"- observations: {len(claims)}",
        "",
        "## Topics",
        "",
    ]
    for tid in sorted(topics):
        lines.append(f"- **{tid}** — {topics[tid]['title']}")
    lines += ["", "## Counts", ""]
    for field in ("claim_kind", "origin", "epistemic_status", "conformance_status"):
        lines.append(f"- by {field}: {counts_by(claims, field)}")
    return "\n".join(lines) + "\n"


def render_counts_table_md(claims: list[dict]) -> str:
    def fmt(counts: dict[str, int]) -> str:
        return " / ".join(f"{k} {v}" for k, v in counts.items())

    rows = [
        ("origin", counts_by(claims, "origin")),
        ("epistemic_status", counts_by(claims, "epistemic_status")),
        ("claim_kind", counts_by(claims, "claim_kind")),
        ("conformance_status", counts_by(claims, "conformance_status")),
    ]
    lines = ["| axis | breakdown |", "|---|---|"]
    lines += [f"| {label} | {fmt(counts)} |" for label, counts in rows]
    return "\n".join(lines)


def update_readme_counts_table(readme_path: Path, claims: list[dict]) -> None:
    """Rewrite the README.md observation-count table from manifest-equivalent counts.

    Re-tallying counts by hand after every observation add/remove/status
    change is exactly the kind of bookkeeping that silently drifts out of
    date. Only the text between the marker pair is replaced; only the first
    START...first-END-after-it pair found is touched.
    """

    text = readme_path.read_text(encoding="utf-8")
    if README_COUNTS_TABLE_START not in text or README_COUNTS_TABLE_END not in text:
        raise CorpusError(
            "README.md is missing the COUNTS_TABLE markers "
            f"({README_COUNTS_TABLE_START!r} / {README_COUNTS_TABLE_END!r}); "
            "cannot auto-update the counts table (were the markers removed?)"
        )
    start_idx = text.index(README_COUNTS_TABLE_START) + len(README_COUNTS_TABLE_START)
    end_idx = text.index(README_COUNTS_TABLE_END)
    if end_idx < start_idx:
        raise CorpusError("README.md COUNTS_TABLE markers are out of order (END before START)")
    new_text = f"{text[:start_idx]}\n{render_counts_table_md(claims)}\n{text[end_idx:]}"
    readme_path.write_text(new_text, encoding="utf-8")
